language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.pip"
  - "sudo python setup.py install"
script:
  - "make test"
  - "gachette -h"
  - "gachette init_config"

notifications:
  email: false
